<?php

namespace HollyIT\FilamentStaticAssets\Tests;

use Faker\Core\File;
use Filament\FilamentServiceProvider;
use Filament\Http\Controllers\AssetController;
use HollyIT\FilamentStaticAssets\StaticAssetsServiceProvider;
use HollyIT\FilamentStaticAssets\Tests\Support\TestingProvider;
use Illuminate\Support\Facades\Route;
use Orchestra\Testbench\TestCase as Orchestra;
class TestCase extends Orchestra
{
    protected string $tempDir;

    protected function setUp(): void
    {
        parent::setUp();
        $this->tempDir = __DIR__ . '/TempPublic';
        Route::get('/assets/{file}', AssetController::class)->where('file', '.*')->name('filament.assets');
        if (!is_dir($this->tempDir)) {
            mkdir($this->tempDir);
        }
    }

    protected function getPackageProviders($app): array
    {
        return [StaticAssetsServiceProvider::class, TestingProvider::class];
    }

    protected function tearDown(): void
    {
        if (is_dir($this->tempDir)) {
            \Illuminate\Support\Facades\File::deleteDirectory($this->tempDir);
        }
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}
